version: 0.1
phases:
  install:
    commands:
      - ls -al
      - echo Installing dependencies...
      - npm install
      - npm install -g serverless
  build:
    commands:
      - echo ${DeployStage}
      - serverless deploy --stage ${DeployStage}
