service:
  name: crypto-API-V2

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 7
  endpointType: regional
  stage: ${env:stage}
  tenant: ""
  app: ""
  environment:
    coinmarketcapProApiKey: ${env:coinmarketcapProApiKey}
    host: ${opt:host}
    username: admin
    password: ${env:dbPassword}

  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "s3:Get*"
     Resource: "*"

functions:
  collectData:
    handler: collectData.handler
    events:
     - schedule:
         name: collectDataSchedule
         description: Collects crypto data from API and records it in DB.
         rate: rate(2 minutes)
         enabled: true
         input:
           coinCount: 5