service:
  name: crypto-API-V2

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 7
  endpointType: regional
  environment:
    coinmarketcapProApiKey: ${opt:coinmarketcapProApiKey}
    host: ${opt:host}
    user: admin
    password: ${opt:password}

  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "s3:Get*"
     Resource: "*"

functions:
  collectData:
    handler: collectData.handler
    events:
     - schedule:
         name: collectData
         description: Collects crypto data from API and records it in DB.
         rate: rate(10 minutes)
         enabled: false